
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#        preferIpAddress: true

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        username: admin_tl
        password: 963317
        url: jdbc:postgresql://db.mypoc.online:5433/thelibrary_loan?currentSchema=dev
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
