spring:
    cloud:
        gateway:
            routes:
            - id: catalog-books
#              uri: http://localhost:8090
              uri: lb://THELIBRARY-MICROSERVICE-CATALOG
              predicates:
              - Path=/api/books/**
        discovery:
            enabled: false
