
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        username: admin_tl
        password: 963317
        url: jdbc:postgresql://mypoc.online:5433/thelibrary_book?currentSchema=dev
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
