
spring:
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/auth/realms/TheLibrary
                        user-name-attribute: preferred_username
                registration:
                    keycloak:
                        client-id: thelibrary-app
                        client-secret: 5902eff4-0127-440d-92d5-f0c0682ff4d7
#
#keycloak:
#    auth-server-url: https://auth.thelibrary.mypoc.online/auth
#    bearer-only: true
#    cors: true
#    public-client: true
#    realm: TheLibrary
#    resource: thelibrary-app
#    security-constraints:
#        #    -   authRoles:
#        #        - user
#        #        - admin
#        #        securityCollections:
#        #        -   methods:
#        #            - GET
#        #            patterns:
#        #            - /api/books/*
#        #            - /api/books
##        -   authRoles:
##                - admin
##            securityCollections:
##                -   patterns:
##                        - /api/*
##                -   methods:
##                        - POST
##                        - PUT
##                    patterns:
##                        - /api/books/*
